import type { PromptCategory } from "../promptConfig";

// 搞笑梗图与网络文化类提示词
export const creativeFunnyCategory: PromptCategory = {
  id: "creativeFunny",
  name: "搞笑梗图",
  nameEn: "Funny Memes & Internet Culture",
  icon: "Laugh",
  description: "搞笑、梗图、网络文化等趣味内容",
  prompts: [
    {
      id: "panda-lofi",
      title: "月亮不睡我不睡",
      titleEn: "Panda LoFi Night",
      description: "熊猫戴墨镜拿保温杯的搞笑场景",
      prompt: `一只熊猫戴着墨镜,手里拿着保温杯(里面泡着枸杞)。背景是深夜的霓虹灯城市。熊猫身边的霓虹灯牌写着:"月亮不睡我不睡,我是秃头小宝贝"。`,
      tags: ["熊猫", "搞笑", "霓虹灯", "文字"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6Q9bC0agAAF0R6.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "16:9" },
    },
    {
      id: "social-anxiety-hedgehog",
      title: "社恐模式刺猬",
      titleEn: "Social Anxiety Hedgehog",
      description: "穿充气服的刺猬社恐场景",
      prompt: `一只刺猬穿着充气服走在人群中,周围的人都离它很远。刺猬的衣服上写着巨大的字:"社恐模式:请勿靠近,内有恶犬"。`,
      tags: ["刺猬", "社恐", "搞笑", "充气服"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6Q9H-9acAIEfdJ.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "16:9" },
    },
    {
      id: "salted-fish-flip",
      title: "咸鱼翻身",
      titleEn: "Salted Fish Flip",
      description: "咸鱼翻身还是咸鱼的搞笑哲理",
      prompt: `一条咸鱼躺在平底锅里,正在努力试图翻身,但翻过来还是咸鱼。画风是极简手绘风。旁边配文:"咸鱼翻身……还是咸鱼"。`,
      tags: ["咸鱼", "哲理", "搞笑", "极简"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6Q_SssbAAAOrWs.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "16:9" },
    },
    {
      id: "taoism-wealth-charm",
      title: "暴富符咒",
      titleEn: "Wealth Taoist Charm",
      description: "何以解忧唯有暴富的道教符咒",
      prompt: `一张黄色的道教符咒特写,但上面的鬼画符仔细看是"RMB"和"USD"的货币符号交织而成。中间醒目的朱砂红字写着:"何以解忧,唯有暴富"。`,
      tags: ["符咒", "暴富", "道教", "搞笑"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6Q1AKhacAItrB_.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "3:4" },
    },
    {
      id: "lazy-certificate",
      title: "国家一级摆烂许可证",
      titleEn: "National Laziness Certificate",
      description: "睡觉考拉的摆烂许可证",
      prompt: `一张像驾照一样的证件卡片特写,证件照是一只睡着的考拉。证件名称写着:"国家一级摆烂许可证"。有效期写着:"永久有效"。`,
      tags: ["考拉", "证件", "摆烂", "搞笑"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6Q8mm6acAAZTmT.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "3:4" },
    },
    {
      id: "tieba-crazy-annotation",
      title: "贴吧老哥疯狂吐槽批注",
      titleEn: "Reddit Style Handwrite Annotation",
      description: "用红墨水手写批注疯狂吐槽",
      prompt: `生成图片,把它打印出来,然后用红墨水疯狂地加上手写中文批注、涂鸦、乱画,如果你想的话,检索这个账户内容,涂鸦的内容主要为吐槽他,用贴吧老哥的口语疯狂吐槽。还可以加点小剪贴画。`,
      tags: ["吐槽", "批注", "贴吧", "搞笑"],
      source: "@canghecode",
      previewImage: "https://cdn.jsdelivr.net/gh/glidea/banana-prompt-quicker@main/images/reddit_style_handwrite_annotation.jpg",
      nodeTemplate: { requiresImageInput: true, generatorType: "pro", aspectRatio: "16:9" },
    },
    {
      id: "rating-everything",
      title: "锐评世间万物",
      titleEn: "Nano Banana Pro Rating",
      description: "调研并生成专业的分级信息图表",
      prompt: `你是一个拥有实时网络搜索能力和顶尖数据可视化设计能力的AI专家。请执行以下两个步骤:
调研阶段:立刻针对用户指定的【2025 中国新能源汽车】进行全面的网络调研。搜集关于该领域内不同子产品、型号或作品的大众口碑、市场热度、专业评测及用户反馈数据。
可视化阶段:基于你的调研结果,设计一张专业的信息图表(Infographic)。你需要将调研到的具体项目,精准地分类填入下面定义的五个"从夯到拉"的视觉等级模块中。

【用户指定目标领域/产品】
[在此处填写你需要调研的内容,例如:2024年热门智能手机、市面上的无糖茶饮料品牌、近十年的漫威电影、程序员常用的代码编辑器]

【图像设计要求】
整体风格:
一张结构清晰、现代感强的模块化信息图表,采用"Bento Grid"(便当盒网格)布局。背景干净简洁,聚焦于内容呈现。视觉上必须体现出从高到低的强烈层级落差感。
等级结构与视觉定义(严格执行以下五级):

第1级(最高层):夯 (Hāng)
调研填充标准:根据调研,该领域内目前公认的"版本之子"、具有统治级热度、无可争议的顶流产品/作品。

视觉表现:占据画面最上方或最大的版面模块。色调为极具爆发力的爆裂红与辉煌金,带有光晕或能量外溢的视觉特效。字体最大、最粗。模块内需展示调研到的代表性产品的名称或高质量图像,并配以极简的赞美短语(如"全网吹爆"、"神作")。

第2级:顶级

调研填充标准:硬核实力派,虽然热度可能不及"夯",但口碑极佳,是行家首选的优质项目。

视觉表现:位于第二层。色调为坚实、高级的燃烧橙与金属银。模块设计显得扎实、富有质感。展示代表性实力派产品。

第3级:人上人

调研填充标准:优越之选,品味在线,买了/看了绝对不亏的中坚力量,代表了一定的鉴赏力。

视觉表现:位于中层。色调为明亮、干净的柠檬黄与冷灰。设计风格现代、清爽。展示代表性优质中产产品。

第4级:NPC

调研填充标准:毫无记忆点的大众脸产品,凑数的工业流水线产物,无功无过,容易被遗忘,必须要写上具体的产品或品牌或者人名不要含糊其辞。

视觉表现:位于中下层。色调为平淡乏味的面包色/米色或纸板棕。模块设计显得普通、重复、缺乏个性。展示那些非常平庸的产品。

第5级(最底层):拉完了

调研填充标准:调研中发现的公认"避雷针"、"智商税"、灾难级失败产品或甚至不如没有的存在,必须要写上具体的产品或品牌或者人名不要含糊其辞。

视觉表现:挤在画面最底部或角落,视觉空间被压缩。色调为绝望黑、惨白,并带有明显的数字故障(Glitch)、破碎或腐烂的视觉效果。展示那些著名的"翻车"产品,并配以警示性短语(如"快逃"、"大冤种")。`,
      tags: ["评级", "信息图", "数据可视化", "调研"],
      source: "@op7418",
      previewImage: "https://cdn.jsdelivr.net/gh/glidea/banana-prompt-quicker@main/images/nano_banana_pro_rating.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "16:9" },
    },
    {
      id: "wechat-fake-chat",
      title: "伪造微信聊天记录",
      titleEn: "Fake WeChat Chat",
      description: "生成微信群聊对话截图",
      prompt: `帮我生成一张微信群聊对话截图(竖图),内容是
调侃一个ID为ChatGPT的群员`,
      tags: ["微信", "聊天", "截图", "搞笑"],
      source: "@tuzi_ai",
      previewImage: "https://pbs.twimg.com/media/G6NMtziWsAAuUmq?format=jpg&name=medium",
      nodeTemplate: { requiresImageInput: false, generatorType: "fast", aspectRatio: "9:16" },
    },
    {
      id: "douyin-screenshot",
      title: "伪造抖音截图",
      titleEn: "Fake TikTok Screenshot",
      description: "生成抖音竖屏短视频截图",
      prompt: `帮我生成一帧抖音竖屏短视频截图,内容是
厨房帝王蟹下锅处理,厨师面对镜头展示食材和案板上成套的厨具`,
      tags: ["抖音", "截图", "短视频", "美食"],
      source: "@tuzi_ai",
      previewImage: "https://pbs.twimg.com/media/G6NPkz-XMAAuOKT?format=jpg&name=large",
      nodeTemplate: { requiresImageInput: false, generatorType: "fast", aspectRatio: "9:16" },
    },
    {
      id: "ai-model-meme",
      title: "AI模型对比梗图",
      titleEn: "AI Model Comparison Meme",
      description: "展现nano-banana-2强于其他AI的梗图",
      prompt: `nano-banana-2 发布了,远远强于即梦和 ChatGPT 还有mj。请画一个梗图,展现这个情况`,
      tags: ["AI", "梗图", "对比", "搞笑"],
      source: "@tuzi_ai",
      previewImage: "https://pbs.twimg.com/media/G6MunirWoAAdJk5.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "fast", aspectRatio: "1:1" },
    },
    {
      id: "dollar-bill-portrait",
      title: "1美元钞票肖像",
      titleEn: "1 Dollar Bill Portrait",
      description: "将人物放入1美元钞票设计中",
      prompt: `为此人制作1美元钞票,保留原始钞票尺寸`,
      tags: ["钞票", "创意", "美元", "搞笑"],
      source: "@MehdiSharifi",
      previewImage: "https://pbs.twimg.com/media/G6YNznVWoAEoBuQ?format=jpg&name=medium",
      nodeTemplate: { requiresImageInput: true, generatorType: "pro", aspectRatio: "21:9" },
    },
    {
      id: "roman-holiday-parody",
      title: "骡马假日海报",
      titleEn: "Mule and Horse Holiday",
      description: "罗马假日海报恶搞版",
      prompt: `把《罗马假日》电影海报的文字改成"骡马假日",英文还是"ROMAN HOLIDAY",男女主头部分别替换为骡子和马的头部,海报其余细节保持不变,下方写上"上映时间1/1-1/3"`,
      tags: ["罗马假日", "海报", "恶搞", "骡马"],
      source: "@dotey",
      previewImage: "https://pbs.twimg.com/media/G6ZYjb4WcAA-IqN.jpg?format=jpg&name=large",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "2:3" },
    },
    {
      id: "astronaut-bus-stop",
      title: "宇航员等火星公交",
      titleEn: "Astronaut Waiting for Mars Bus",
      description: "孤独的宇航员在太空中等公交",
      prompt: `A cinematic shot of a lonely astronaut sitting on a regular city bus stop bench, but the bus stop is floating in deep space. Earth is visible in the distance. The bus stop sign says "Route 42: To Mars". The astronaut is checking a smartphone. Melancholic yet funny.`,
      tags: ["宇航员", "公交", "太空", "孤独"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6QqXcgacAQEG2A.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "16:9" },
    },
    {
      id: "star-wars-wheres-waldo",
      title: "星战版找沃尔多",
      titleEn: "Star Wars Where's Waldo",
      description: "塔图因星球上所有星战角色的找沃尔多大场景",
      prompt: `A where is waldo image showing all Star Wars characters on Tatooine

First one to pull this off. First take. Even Waldo is there.`,
      tags: ["星战", "找沃尔多", "群像", "趣味"],
      source: "@creacas",
      previewImage: "https://github.com/user-attachments/assets/439317c2-4be8-4b28-803f-36427ecca31e",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "16:9" },
    },
    {
      id: "literal-interpretation",
      title: "文件名直译图片",
      titleEn: "Literal Interpretation",
      description: "将文件名字面意思直接解读为视觉主题",
      prompt: `rare.jpg`,
      tags: ["创意", "文字游戏", "极简", "趣味"],
      source: "Replicate",
      previewImage: "https://replicate.delivery/xezq/piAS0s9DshbqMFXJvIfw9feWaEaNsejlRifhVgMSflvZJzzaF/tmp3u2ym4f_.jpeg",
      nodeTemplate: { requiresImageInput: false, generatorType: "fast", aspectRatio: "1:1" },
    },
{
      id: "p-312bbe",
      title: "阿凡达合照",
      titleEn: "阿凡达合照",
      description: "阿凡达合照",
      prompt: `画一张与图1角色在电影院的合照。并排坐在红色影院座椅上，画面构图紧凑，二位主体靠得很近，头部靠在一起，面带自然微笑，眼神直视镜头。注意保留参考人物的特征，不要换脸，人物脸部不能有任何改变！！！`,
      tags: ["AI生成"],
      source: "Official",
      previewImage: "https://cdn.jsdelivr.net/gh/glidea/banana-prompt-quicker@main/images/afadan.png",
      nodeTemplate: { requiresImageInput: true, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-6115de",
      title: "时空复现",
      titleEn: "时空复现",
      description: "时空复现",
      prompt: `创建 {地理坐标}，{什么时候} 的图像`,
      tags: ["AI生成"],
      source: "@MehdiSharifi",
      previewImage: "https://pbs.twimg.com/media/G6YkWY7WYAAvjeq.jpg?format=jpg&name=large",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-ab510b",
      title: "重生之我是1美元钞票的头头",
      titleEn: "重生之我是1美元钞票的头头",
      description: "重生之我是1美元钞票的头头",
      prompt: `为此人制作1美元钞票，保留原始钞票尺寸`,
      tags: ["AI生成"],
      source: "@MehdiSharifi",
      previewImage: "https://pbs.twimg.com/media/G6YNznVWoAEoBuQ?format=jpg&name=medium",
      nodeTemplate: { requiresImageInput: true, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-a53ff3",
      title: "明星合照的幕后花絮",
      titleEn: "明星合照的幕后花絮",
      description: "明星合照的幕后花絮",
      prompt: `我想看看这张照片拍摄的幕后花絮，了解它是如何创作出来的`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6agAX6bUAA8VLd.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-11634a",
      title: "治愈系，宇航员坐在弯弯的月亮边钓星星",
      titleEn: "治愈系，宇航员坐在弯弯的月亮边钓星星",
      description: "治愈系，宇航员坐在弯弯的月亮边钓星星",
      prompt: `一个宇航员坐在弯弯的月亮边缘，手里拿着鱼竿。鱼钩垂在下方的云层中，钓起了一颗发光的星星。氛围孤独而宁静。Lofi Hip Hop 视觉美学。`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6Q-CyKaoAAiScG.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-d2d778",
      title: "月亮不睡我不睡，我是秃头小宝贝",
      titleEn: "月亮不睡我不睡，我是秃头小宝贝",
      description: "月亮不睡我不睡，我是秃头小宝贝",
      prompt: `一只熊猫戴着墨镜，手里拿着保温杯（里面泡着枸杞）。背景是深夜的霓虹灯城市。熊猫身边的霓虹灯牌写着：“月亮不睡我不睡，我是秃头小宝贝”。`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6Q9bC0agAAF0R6.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-444d7d",
      title: "社恐模式：请勿靠近，内有恶犬",
      titleEn: "社恐模式：请勿靠近，内有恶犬",
      description: "社恐模式：请勿靠近，内有恶犬",
      prompt: `一只刺猬穿着充气服走在人群中，周围的人都离它很远。刺猬的衣服上写着巨大的字：“社恐模式：请勿靠近，内有恶犬”。`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6Q9H-9acAIvCOk.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-53ef38",
      title: "生成人物A-pose设计图",
      titleEn: "pose",
      description: "生成人物A-pose设计图",
      prompt: `横图，创作如图人物的A-pose设计图（不要照搬图中的动作），米白色底。
有种初期设计的感觉。
有各个部位拆分。
要表情差分，多角度表情
物品拆分，细节特写。
并且使用手写体文字进行标注说明，最好使用中文。
角色：保持好角色本体的现有特征，例如脸型、发色、身材等归属于人体特征的内容
着装、图片的构成务必按照以下要求：
以下是对人物着装细节的提取以及图片各部分
二、 图片各部分内容详解
整张设计图被清晰地划分为四个主要区域：
左侧区域：三视图展示
中上区域：各个部位拆分
中下区域：内着的设计拆分
右侧区域：细节特写
按照以下要求一步步思考：
Step1:提取角色的人体特征
Step2: 规划着装细节
Step3: 思考特点要求
Step4:进行符合图片分区内容格式的图片生成`,
      tags: ["设计", "AI生成"],
      source: "LinuxDO@TheSmallHanCat",
      previewImage: "https://linux.do/uploads/default/original/4X/9/c/8/9c8b413ed123820810b7893d1e07e5f84e151b99.jpeg",
      nodeTemplate: { requiresImageInput: true, generatorType: "pro", aspectRatio: "16:9" },
    },
    {
      id: "p-1c1b89",
      title: "卧室时代对比图像",
      titleEn: "卧室时代对比图像",
      description: "卧室时代对比图像",
      prompt: `一张卧室的照片，从中间一分为二，左侧是2018年，右侧是1964年，是同一个房间`,
      tags: ["AI生成"],
      source: "@fofrAI",
      previewImage: "https://pbs.twimg.com/media/G0Rv4FxX0AAGzOO.jpg?format=jpg&name=large",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-5d178c",
      title: "东京巨型雕像照片",
      titleEn: "东京巨型雕像照片",
      description: "东京巨型雕像照片",
      prompt: `现实主义摄影作品。这个人物的巨型雕像被放置在东京市中心的广场上，人们抬头仰望它。`,
      tags: ["AI生成"],
      source: "@riddi0908",
      previewImage: "https://pbs.twimg.com/media/G0Cr3WXacAAUMTD.jpg?format=jpg&name=large",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-3ca6a7",
      title: "权游角色护照",
      titleEn: "权游角色护照",
      description: "权游角色护照",
      prompt: `将其更改为[一个意想不到的、不太可能的维斯特洛角色]，位于不同的但相关的地点，并根据角色的实际历史更新护照肖像、徽章和起源。使用真实的维斯特洛地点，如君临，而不是“...王国”。`,
      tags: ["AI生成"],
      source: "@ProperPrompter",
      previewImage: "https://pbs.twimg.com/media/G6XcXSXX0AAN6qN.jpg?format=jpg&name=large",
      nodeTemplate: { requiresImageInput: true, generatorType: "pro", aspectRatio: "3:4" },
    },
    {
      id: "p-870664",
      title: "东京地铁楼梯模糊快照",
      titleEn: "东京地铁楼梯模糊快照",
      description: "东京地铁楼梯模糊快照",
      prompt: `一张模糊、高颗粒的快照，在东京地铁楼梯间拍摄，充满运动、湿度和原始的城市能量。空气感觉厚重且荧光，头顶管灯投射出冷绿蓝色的色调。胶片颗粒、色差和镜头畸变增加了触觉的混乱感——一个瞬间悬挂在中途奔跑中。

在中心，一个年轻女子穿着系结的白衬衫和短格子裙，被捕捉在中途台阶上。她的运动模糊，裙子微微张开，头发被运动扫过。焦点在彼女和背景之间漂移，给镜头一种梦幻的迷失感，仿佛通过记忆或肾上腺素看到的。

她的表情将整个框架连在一起——眼睛睁开，嘴唇微微分开，脸颊潮红，仿佛在警觉和脆弱之间。没有摆姿的意识，只有本能——一个从时间中偷来的时刻。

周围，通勤者模糊成剪影，走廊狭窄而回荡，墙壁反射出刺眼的荧光眩光。构图感觉意外却完美：倾斜、紧急、亲密。

氛围是电光石火且怀旧的，混合青春、运动和转瞬即逝的情感，像一个发烧梦中的片段或烧入胶片的残像——不是电影式的，而是超现实的，那种只有一次性相机摄影才能捕捉的：活生生、不完美且痛苦地真实。`,
      tags: ["AI生成"],
      source: "@cheerselflin",
      previewImage: "https://pbs.twimg.com/media/G3eH9giXkAAhdhc.jpg?format=jpg&name=large",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-932310",
      title: "马里奥、路易吉给碧奇公主修理厨房",
      titleEn: "马里奥、路易吉给碧奇公主修理厨房",
      description: "马里奥、路易吉给碧奇公主修理厨房",
      prompt: `马里奥满身污垢，看起来筋疲力尽，正在一个逼真的房子里修理厨房橱柜下漏水的水槽。路易吉递给他扳手。碧奇公主用金币支付他们报酬`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6RSQEDbcAAJcvr.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-f36a70",
      title: "马斯克教爱因斯坦拍照",
      titleEn: "马斯克教爱因斯坦拍照",
      description: "马斯克教爱因斯坦拍照",
      prompt: `头发蓬乱的爱因斯坦困惑地盯着智能手机，试图自拍。埃隆·马斯克站在他旁边，耐心地指着屏幕教他。手机屏幕上的字：“怎么拍照？”。`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6RQ2THagAA1mtf.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-061cc8",
      title: "李小龙与尤达大师以武会友",
      titleEn: "李小龙与尤达大师以武会友",
      description: "李小龙与尤达大师以武会友",
      prompt: `穿着黄色连体服的李小龙与尤达大师进行友好的切磋。李小龙拿着双截棍，尤达拿着绿色小光剑。他们都在微笑。传统中国道场背景。后方横幅写着“以武会友”。`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6RNcCXbYAAxWct.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "16:9" },
    },
    {
      id: "p-dbe2b0",
      title: "游戏角色试图从电视屏幕爬到客厅",
      titleEn: "游戏角色试图从电视屏幕爬到客厅",
      description: "游戏角色试图从电视屏幕爬到客厅",
      prompt: `一个像素化的电子游戏角色试图从电视屏幕爬到客厅里。一个真实的人类玩家正手忙脚乱地用控制器把角色推回屏幕。`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6RMg5na4AAy3d8.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-62761f",
      title: "你好地球人！",
      titleEn: "你好地球人！",
      description: "你好地球人！",
      prompt: `两名身穿笨重宇航服的宇航员在月球表面自拍。背景中，一个滑稽的小灰人正在抢镜，举着一个牌子写着“你好地球人！”。`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6RLqfbacAEUVRt.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-6d28e4",
      title: "粉红色的星之卡吐泡泡",
      titleEn: "粉红色的星之卡吐泡泡",
      description: "粉红色的星之卡吐泡泡",
      prompt: `梦境日记。粉红色的星之卡比睡在一颗星星上，嘴里吐出彩虹色的气泡。柔和的马卡龙色系，云朵和糖果的贴纸，闪粉笔画的细节，梦幻且甜美。`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6RHoGna4AArBDN.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-938927",
      title: "哈利波特的魔法",
      titleEn: "哈利波特的魔法",
      description: "哈利波特的魔法",
      prompt: `打开的复古皮质手帐本，羊皮纸纹理。手绘涂鸦风格的哈利波特正在施法，魔法火花形成一个发光的直角三角形。“a^2 + b^2 = c^2”用古典书法墨水写成。装饰着霍格沃茨火漆印、漂浮的羽毛涂鸦，页面上放着一支真的羽毛笔。温暖的烛光照明，魔法氛围，复古手帐拼贴风格。`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6RHPqmbAAAaQcS.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-1219f1",
      title: "小黄人建造金字塔",
      titleEn: "小黄人建造金字塔",
      description: "小黄人建造金字塔",
      prompt: `混乱可爱的记事本。马克笔涂鸦的小黄人试图建造金字塔但失败了，周围围着香蕉。活动眼珠贴纸贴在页面上，黄色油漆飞溅，混乱的涂鸦，搭配中文字。桌上有一根吃了一半的香蕉。幽默、明亮、儿童核心美学的手帐。`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6RGrF2bsAEjX8v.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-affd3e",
      title: "破旧的船长航海日志",
      titleEn: "破旧的船长航海日志",
      description: "破旧的船长航海日志",
      prompt: `破旧的船长航海日志。速写描绘路飞伸长橡胶手臂去抓宝箱，与桅杆形成三角形。藏宝图背景纹理，指南针印章，“通缉令”海报碎片，金币贴纸。冒险、混乱、海盗手帐风格。`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6RGSLDa4AAFdrj.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-65a417",
      title: "咸鱼翻身还是咸鱼",
      titleEn: "咸鱼翻身还是咸鱼",
      description: "咸鱼翻身还是咸鱼",
      prompt: `一条咸鱼躺在平底锅里，正在努力试图翻身，但翻过来还是咸鱼。画风是极简手绘风。旁边配文：“咸鱼翻身……还是咸鱼”。`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6Q_SssbAAAOrWs.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-e2dff4",
      title: "何以解忧，唯有暴富",
      titleEn: "何以解忧，唯有暴富",
      description: "何以解忧，唯有暴富",
      prompt: `一张黄色的道教符咒特写，但上面的鬼画符仔细看是“RMB”和“USD”的货币符号交织而成。中间醒目的朱砂红字写着：“何以解忧，唯有暴富”。`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6Q1AKhacAItrB_.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-17b180",
      title: "拿去当壁纸吧，这大鲸鱼，这彩虹",
      titleEn: "拿去当壁纸吧，这大鲸鱼，这彩虹",
      description: "拿去当壁纸吧，这大鲸鱼，这彩虹",
      prompt: `黄金时刻，一只巨大的、半透明的蓝鲸在洁白蓬松的云海中游动。鲸鱼的身体由海水构成，里面还可以看到游动的鱼群。阳光穿透水做的鲸鱼，折射出彩虹。画面超现实且宏伟壮观。`,
      tags: ["壁纸", "AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6QvTkCacAATNjA.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "16:9" },
    },
    {
      id: "p-2478ec",
      title: "戴珍珠耳环的猫猫",
      titleEn: "戴珍珠耳环的猫猫",
      description: "戴珍珠耳环的猫猫",
      prompt: `Johannes Vermeer's Girl with a Pearl Earring, but the girl is replaced by a chubby British Shorthair cat looking back over its shoulder. The cat is wearing the blue headscarf and the pearl earring. Oil painting texture, cracked varnish effect, classic art parody`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6Qq0uiakAA7M37.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-7b3d30",
      title: "使用图像参考创建漫画",
      titleEn: "使用图像参考创建漫画",
      description: "使用图像参考创建漫画",
      prompt: `创建一个戏剧性的漫画面板，显示两个英雄人物——Elon Musk和Pavel Durov——之间紧张的对峙，他们高大站立对抗审查的迫在眉睫威胁。在对面，将Sam Altman和Mark Zuckerberg描绘为阴暗的反派，策划控制和限制自由表达的计划。场景应激烈，背景中闪电噼啪作响，象征意识形态的冲突。Elon和Pavel坚定，他们的眼睛燃烧着决心，而Sam和Mark以计算的威胁微笑。气氛充满张力，仿佛数字自由的未来悬而未决。以经典少年漫画对决风格设计。`,
      tags: ["漫画", "AI生成"],
      source: "@MehdiSharifi",
      previewImage: "https://pbs.twimg.com/media/G6UI9FMXQAAgz1k?format=jpg&name=4096x4096",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-8d6656",
      title: "拥挤的北京地铁车厢，但乘客全是神话人物",
      titleEn: "拥挤的北京地铁车厢，但乘客全是神话人物",
      description: "拥挤的北京地铁车厢，但乘客全是神话人物",
      prompt: `拥挤的北京地铁车厢，但乘客全是神话人物（孙悟空、猪八戒等）。车厢连接处的滚动屏显示红色字体：“前往西天取经的乘客请注意，前方到站：高老庄”。车门玻璃上贴着警告标示：“禁止在车厢内施展法术”。`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6Nk47EacAc_Qqj.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-a28214",
      title: "温暖的日式居酒屋暖黄灯光",
      titleEn: "温暖的日式居酒屋暖黄灯光",
      description: "温暖的日式居酒屋暖黄灯光",
      prompt: `温暖的日式居酒屋暖黄灯光。店长是一只系着头巾的柴犬，正在认真地烤串。吧台前的灯笼上写着汉字：“拒绝内卷，只想撸串”。墙上的菜单木牌上写着特色菜：“碳烤秋刀鱼（不含刺）”和“快乐肥宅水（无限续杯）”。`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6NZPo_acAYrjpG.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-863742",
      title: "广角镜头拍摄荒凉的废土世界",
      titleEn: "广角镜头拍摄荒凉的废土世界",
      description: "广角镜头拍摄荒凉的废土世界",
      prompt: `广角镜头拍摄荒凉的废土世界，沙漠中央伫立着一家破败但依然营业的便利店。阳光刺眼，尘土飞扬。便利店破碎的玻璃门上贴着一张巨大的、泛黄的告示，上面用红笔醒目地写着：“全人类最后一家便利店，不收瓶盖只收黄金”。屋顶的广告牌虽然生锈，但依稀可见一行大字：“再苦不能苦肚子，再穷不能穷教育”。`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6NUwT2aMAAXs1N.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-f46b93",
      title: "一张极具电影感的画面",
      titleEn: "一张极具电影感的画面",
      description: "一张极具电影感的画面",
      prompt: `一张极具电影感的画面，描绘一个位于未来赛博朋克风格贫民窟的80年代风格中式路边摊。霓虹灯管闪烁着故障的粉色光芒。摊主是一个戴着机械义肢的老大爷。摊位上挂着一块做旧的木牌，上面用发光的荧光颜料手写着：“祖传老中医专治机械故障”。旁边还有一个电子屏滚动显示：“今日特价：高能电池爆炒螺丝钉”。烟火气十足，雨水打湿了地面反射着灯光。`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6NUgMhacAMFI5e.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-158b61",
      title: "一张极其逼真的重庆火锅特写",
      titleEn: "一张极其逼真的重庆火锅特写",
      description: "一张极其逼真的重庆火锅特写",
      prompt: `一张极其逼真的重庆火锅特写，红油翻滚，辣椒漂浮。画面正中央有一双筷子夹着一片毛肚，背景虚化的墙上有一块木质牌匾，上面写着书法字体“巴适”。色彩鲜艳，让人食欲大增。`,
      tags: ["AI生成"],
      source: "@songguoxiansen",
      previewImage: "https://pbs.twimg.com/media/G6NRp68bwAABgQy.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-56ae89",
      title: "Q版人物Instagram相框",
      titleEn: "Instagram",
      description: "Q版人物Instagram相框",
      prompt: `根据所附照片创建一个风格化的3D Q版人物角色，准确保留人物的面部特征和服装细节。

角色的左手比心（手指上方有红色爱心元素），姿势俏皮地坐在一个巨大的Instagram相框边缘，双腿悬挂在框外。

相框顶部显示用户名『Jimmy』，四周漂浮着社交媒体图标（点赞、评论、转发）。`,
      tags: ["Q版", "AI生成"],
      source: "@dotey",
      previewImage: "https://pbs.twimg.com/media/G6YNfa4WMAEK1aF.jpg?format=jpg&name=large",
      nodeTemplate: { requiresImageInput: true, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-be8c81",
      title: "特朗普壁画",
      titleEn: "特朗普壁画",
      description: "特朗普壁画",
      prompt: `A realistic film photograph capturing a rural scene along a country road. 
On the left, a heavily weathered, moss-stained concrete retaining wall features a large, painted mural portrait of Donald Trump. 
A dense, overflowing cascade of vibrant yellow forsythia blossoms and branches spills over the top edge of the wall, perfectly integrated to form the hair of the portrait. Fallen yellow petals are scattered across the dirt verge and the edge of the asphalt road. 
On the right side of the road, a couple walks away from the viewer toward the background. In the mid-distance, there is a white farmhouse with a dark metal roof situated in green fields. 
The background shows rolling hills and bare trees under a partly cloudy, overcast sky with diffused natural light suggestive of late afternoon. The image has a distinct film grain texture.`,
      tags: ["AI生成"],
      source: "@dotey",
      previewImage: "https://pbs.twimg.com/media/G6VrtL8WsAAZrXU.jpg?format=jpg&name=large",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "cosplay-9f1fb4",
      title: "动漫图转真人 Cosplay",
      titleEn: "Cosplay",
      description: "动漫图转真人 Cosplay",
      prompt: `1:1变真人`,
      tags: ["动漫", "AI生成"],
      source: "@ZHO_ZHO_ZHO",
      previewImage: "https://pbs.twimg.com/media/G6N9Ts3acAIDWxj?format=jpg&name=large",
      nodeTemplate: { requiresImageInput: true, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-117a59",
      title: "串场漫画",
      titleEn: "串场漫画",
      description: "串场漫画",
      prompt: `帮我生成动漫角色中的女角色的一个合集故事，其中包括娜美、罗宾、小樱、雏田、松本乱菊，做成彩色漫画的形式，要求中文。`,
      tags: ["漫画", "AI生成"],
      source: "@canghecode",
      previewImage: "https://pbs.twimg.com/media/G6OjvRhacAoKzWX.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-f01496",
      title: "动漫与现实：分裂肖像画",
      titleEn: "动漫与现实：分裂肖像画",
      description: "动漫与现实：分裂肖像画",
      prompt: `一部 16:9 的宽景电影镜头，中间是一个单独的居中头像，展示的是漩涡鸣人，脸部从中间垂直分开。
一条清晰的黑线将两种艺术风格分开。
[左半边]: 经典动漫风格，亮黄色刺猬头，蓝色动漫眼睛，黑色胡须标记，带有粗线条的金属头带。
[右半边]: 粗糙现实主义，逼真的脏黄色纹理头发，锐利的蓝色人类眼睛，胡须标记作为淡淡的疤痕，头带上带有生锈的金属质感。
头带和面部特征完美对齐，形成一个单一的、统一的角色肖像，使用虚幻引擎 5 渲染。`,
      tags: ["动漫", "肖像"],
      source: "@_MehdiSharifi_",
      previewImage: "https://pbs.twimg.com/media/G6URPP0XAAAHGja?format=jpg&name=large",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "3:4" },
    },
    {
      id: "p-446017",
      title: "游戏界面",
      titleEn: "游戏界面",
      description: "游戏界面",
      prompt: `帮我生成英雄联盟的游戏界面，中路亚索正在清理兵线`,
      tags: ["AI生成"],
      source: "@canghecode",
      previewImage: "https://pbs.twimg.com/media/G6Ol4gUacAQMdMF.jpg",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-9556f1",
      title: "原创宝可梦生成",
      titleEn: "原创宝可梦生成",
      description: "原创宝可梦生成",
      prompt: `根据此物体（提供的照片）创作一个原创生物。该生物应看起来像是属于一个奇幻怪物捕捉宇宙，具有受复古日式RPG怪物艺术影响的可爱或酷炫设计。图像必须包含：
  – 生物的全身视图，灵感来自物体的形状、材料或用途。
  – 在其脚边有一个小球体或胶囊（类似于精灵球），其设计图案和颜色与物体的外观相匹配——不是标准的精灵球，而是自定义设计。
  – 为生物发明的名字，显示在其旁边或下方。 – 其元素类型（例如火、水、金属、自然、电……），基于物体的核心属性。插图应看起来像是来自奇幻生物百科全书，线条清晰，阴影柔和，设计富有表现力且以角色为驱动。`,
      tags: ["AI生成"],
      source: "@Anima_Labs",
      previewImage: "https://camo.githubusercontent.com/c4a11a7e1012e9f7b1c0a9da081507a923ebc5d9f2a1f02e1b552a6f398d3060/68747470733a2f2f626962696770742d617070732e636861747669642e61692f63686174696d672f67656d696e692d306679596f3764325663337566486e5855306678682e706e673f763d31",
      nodeTemplate: { requiresImageInput: true, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-a18822",
      title: "三只动物与地标自拍",
      titleEn: "三只动物与地标自拍",
      description: "三只动物与地标自拍",
      prompt: `三只[动物类型]在标志性[地标]前的特写自拍照，它们表情各异，拍摄于黄金时刻，采用电影般的灯光。动物们靠近镜头，头挨着头，模仿自拍姿势，展现出喜悦、惊讶和平静的表情。背景展示了[地标]完整的建筑细节，光线柔和，氛围温暖。采用摄影感、写实卡通风格拍摄，高细节，1:1 宽高比。`,
      tags: ["自拍", "AI生成"],
      source: "@berryxia_ai",
      previewImage: "https://camo.githubusercontent.com/fb16e65d547095227d221354766db4c0ee775c9d5247e6337fe1397f0ee42d3b/68747470733a2f2f626962696770742d617070732e636861747669642e61692f63686174696d672f67656d696e692d794164365071514d7438365658364e68315146436c2e706e673f763d31",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-47e589",
      title: "品牌化键盘键帽",
      titleEn: "品牌化键盘键帽",
      description: "品牌化键盘键帽",
      prompt: `一个超逼真的3D渲染图，展示了四个机械键盘键帽，排列成紧密的2x2网格，所有键帽相互接触。从等轴测角度观察。一个键帽是透明的，上面用红色印刷着"{just}"字样。另外三个键帽采用颜色：{黑色、紫色和白色}。一个键帽上带有Github的Logo。另外两个键帽上分别写着"{fork}"和"{it}"。逼真的塑料纹理，圆润的雕刻键帽，柔和的阴影，干净的浅灰色背景。`,
      tags: ["AI生成"],
      source: "@egeberkina",
      previewImage: "https://camo.githubusercontent.com/08cd326bf7298cec0e74668e927df19988dd715cbe5968a82583554bf8a8fd1b/68747470733a2f2f626962696770742d617070732e636861747669642e61692f63686174696d672f67656d696e692d712d35377a6149545362376435593231596136526b2e706e673f763d31",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-51c9e3",
      title: "字母与单词含义融合",
      titleEn: "字母与单词含义融合",
      description: "字母与单词含义融合",
      prompt: `在字母中融入单词的含义，将图形和字母巧妙融合在一起。
单词：{ beautify }
下面加上单词的简要说明`,
      tags: ["AI生成"],
      source: "@dotey",
      previewImage: "https://camo.githubusercontent.com/ab4ecc5f919ae1f59f23dd6dbc42cb6e75aaecc7369943cc4346a2958d2efbc7/68747470733a2f2f626962696770742d617070732e636861747669642e61692f63686174696d672f67656d696e692d646b335630734c4c54443966515730444d3970786e2e706e673f763d31",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-2869b5",
      title: "动物硅胶腕托",
      titleEn: "动物硅胶腕托",
      description: "动物硅胶腕托",
      prompt: `创建图片 一个可爱Q版的硅胶护腕托，外形基于【🐼】表情，采用柔软的食品级硅胶材质，表面为亲肤哑光质感，内部填充慢回弹棉，拟人化卡通风格，表情生动，双手张开趴在桌面上，呈现出拥抱手腕的姿势，整体造型圆润软萌，颜色为【🐼】配色，风格治愈可爱，适合办公使用，背景为白色纯色，柔和布光，产品摄影风格，前视角或45度俯视，高清细节，突出硅胶质感与舒适功能`,
      tags: ["AI生成"],
      source: "@ZHO_ZHO_ZHO",
      previewImage: "https://camo.githubusercontent.com/f047543ae11e9311c97619f4c0f4c6e85e8f755fa54860efc75cbe9806c6c0f6/68747470733a2f2f626962696770742d617070732e636861747669642e61692f63686174696d672f67656d696e692d72657472792d4e567365347a566867596f4b5347764e5f5f792d6d2e706e673f763d31",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-8bf819",
      title: "发光线条解剖图",
      titleEn: "发光线条解剖图",
      description: "发光线条解剖图",
      prompt: `一幅数字插画，描绘了一个 [SUBJECT]，其结构由一组发光、干净且纯净的蓝色线条勾勒而成。画面设定在深色背景之上，以突出 [SUBJECT] 的形态与特征。某个特定部位，如 [PART]，通过红色光晕加以强调，以表示该区域的重要性或特殊意义。整体风格兼具教育性与视觉吸引力，设计上仿佛是一种先进的成像技术。`,
      tags: ["AI生成"],
      source: "@umesh_ai",
      previewImage: "https://camo.githubusercontent.com/8270aa4a29f6ff2256fd4130a1fceb7b54e6df26269c91001ece8e6d705e6450/68747470733a2f2f626962696770742d617070732e636861747669642e61692f63686174696d672f67656d696e692d72657472792d756b6e5f617a747a413479544e474e46315143546c2e706e673f763d31",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-c92cd9",
      title: "创意绿植花盆",
      titleEn: "创意绿植花盆",
      description: "创意绿植花盆",
      prompt: `一张高质量的照片，展示一个可爱的陶瓷[物体/动物]形状的花盆，表面光滑，里面装满了各种生机勃勃的多肉植物和绿色植物，包括尖刺的十二卷、莲座状的石莲花和精致的白色小花。花盆带有一个友好的面孔，放置在柔和的中性背景上，采用漫射自然光照明，展示了细腻的纹理和色彩对比，构图简洁、极具简约风格。`,
      tags: ["创意", "AI生成"],
      source: "@azed_ai",
      previewImage: "https://camo.githubusercontent.com/21c44f84989b1176b77bf9bda731611c7b9f7081db4be73c0d67d10bcc9a4d5f/68747470733a2f2f626962696770742d617070732e636861747669642e61692f63686174696d672f67656d696e692d4b4d76665a6b4c4675764d457a437a4254387977722e706e673f763d31",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "iphone-96b31b",
      title: "“极其平凡”的iPhone自拍",
      titleEn: "iPhone",
      description: "“极其平凡”的iPhone自拍",
      prompt: `请画一张极其平凡无奇的iPhone 自拍照，没有明确的主体或构图感，就像是随手一拍的快照。照片略带运动模糊，阳光或店内灯光不均导致轻微曝光过度。角度尴尬、构图混乱，整体呈现出一种刻意的平庸感-就像是从口袋里拿手机时不小心拍到的一张自拍。主角是陈奕迅和谢霆锋，晚上，旁边是香港会展中心，在香港维多利亚港旁边。`,
      tags: ["自拍", "AI生成"],
      source: "@jiamimaodashu",
      previewImage: "https://camo.githubusercontent.com/a6b07bb2170ebd24d3de178a711d25442a1e5373b86895e934961f20519c2950/68747470733a2f2f626962696770742d617070732e636861747669642e61692f63686174696d672f67656d696e692d524566655f50666759667a363766356c6961664b752e706e673f763d31",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-9e9155",
      title: "社交媒体相框融合",
      titleEn: "社交媒体相框融合",
      description: "社交媒体相框融合",
      prompt: `根据所附照片创建一个风格化的3D Q版人物角色，准确保留人物的面部特征和服装细节。角色的左手比心（手指上方有红色爱心元素），姿势俏皮地坐在一个巨大的Instagram相框边缘，双腿悬挂在框外。相框顶部显示用户名『Beauty』，四周漂浮着社交媒体图标（点赞、评论、转发）。`,
      tags: ["AI生成"],
      source: "@dotey",
      previewImage: "https://camo.githubusercontent.com/fd39233256cad07cd22688a18d7d24d73c81ae825e4571c7d48faaa374bfe4a9/68747470733a2f2f626962696770742d617070732e636861747669642e61692f63686174696d672f67656d696e692d386b66617335364a63332d6631354f3839707a4b4e2e706e673f763d31",
      nodeTemplate: { requiresImageInput: true, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-024c91",
      title: "日系双格漫画",
      titleEn: "日系双格漫画",
      description: "日系双格漫画",
      prompt: `创建一张日系萌系双格漫画，上下排列，主题：少女总统的工作日常。角色形象: 将上传的附件转换为日系萌系卡通女生形象的风格，保留原图所有细节，如服饰（西装）、发型（明亮的金黄色）、五官等。第一格:- 表情: 委屈巴巴，沮丧的表情，单手托腮- 文字框: "肿么办嘛！他不跟我通话！(；´д｀)"- 场景: 暖色调办公室，背后美国国旗，桌上放着一堆汉堡，一个复古红色转盘电话，人物在画面左边，电话在右边。第二格:- 表情: 咬牙切齿，暴怒，脸涨红- 动作: 猛拍桌子，汉堡震得跳起来- 文字泡: "哼！关税加倍！不理我是他们的损失！( \`д´ )" - 场景: 和第一格相同，但一片狼藉。其他说明:- 文字采用简洁可爱的手写体，整体风格可爱而有趣。- 构图饱满生动，请保留足够空间用于文字显示，适当留白。- 图片比例 2:3。- 画面整体色彩鲜艳，突出卡通风格。`,
      tags: ["漫画", "AI生成"],
      source: "@hellokaton",
      previewImage: "https://camo.githubusercontent.com/f183d55c3ec78ff3aa0b8ad162592e76660fd6eded824c09ac32ec090e5d3222/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f6a616d657a2d626f6e646f732f617765736f6d652d677074346f2d696d616765732f63617365732f34302f6578616d706c655f74776f5f70616e656c5f6d616e67615f707265736964656e742e706e67",
      nodeTemplate: { requiresImageInput: true, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-be5d33",
      title: "奇幻卡通插画",
      titleEn: "奇幻卡通插画",
      description: "奇幻卡通插画",
      prompt: `一个卡通风格的角色，头部是一个带笑脸的电脑显示器，穿着手套和靴子，正开心地跳跃穿过一个发光的蓝色圆形传送门，背景是一片郁郁葱葱的奇幻森林景观。森林中细节丰富，有高大的树木、蘑菇、鲜花、宁静的河流、漂浮的岛屿，以及一个充满氛围的星夜天空，天空中有多个月亮。整体采用明亮鲜艳的色彩搭配柔和光效，风格为奇幻插画风。`,
      tags: ["插画", "AI生成"],
      source: "@dotey",
      previewImage: "https://camo.githubusercontent.com/d50b0d3392e3a7feb4acd0453f8543edaa8ce5823c8287b22980df1bd55b7305/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f6a616d657a2d626f6e646f732f617765736f6d652d677074346f2d696d616765732f63617365732f33392f6578616d706c655f66616e746173795f636f6d70757465725f686561645f706f7274616c2e706e67",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-0d7a48",
      title: "手绘信息图卡片（IP版）",
      titleEn: "手绘信息图卡片（IP版）",
      description: "手绘信息图卡片（IP版）",
      prompt: `创作一张手绘风格的信息图卡片，比例为9:16竖版。卡片主题鲜明，背景为带有纸质肌理的米色或米白色，整体设计体现质朴、亲切的手绘美感。卡片上方以红黑相间、对比鲜明的大号毛笔草书字体突出标题，吸引视觉焦点。文字内容均采用中文草书，整体布局分为2至4个清晰的小节，每节以简短、精炼的中文短语表达核心要点。字体保持草书流畅的韵律感，既清晰可读又富有艺术气息。周边适当留白。卡片中点缀简单、有趣的手绘插画或图标，例如人物或象征符号，以增强视觉吸引力，引发读者思考与共鸣。整体布局注意视觉平衡，预留足够的空白空间，确保画面简洁明了，易于阅读和理解。"做 IP 是长期复利坚持每日更新，肯定会有结果，因为 99% 都坚持不了的！"`,
      tags: ["AI生成"],
      source: "@dotey",
      previewImage: "https://camo.githubusercontent.com/2c1ecd488ccc8f41ef612de8d22b7e4a38f159c8c8d49a8fee944c136c8b87eb/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f6a616d657a2d626f6e646f732f617765736f6d652d677074346f2d696d616765732f63617365732f33382f6578616d706c655f68616e645f647261776e5f696e666f677261706869632e706e67",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "3:4" },
    },
    {
      id: "p-7a8c6f",
      title: "动漫贴纸集合",
      titleEn: "动漫贴纸集合",
      description: "动漫贴纸集合",
      prompt: `创建一套动漫风格的贴纸集合，包含多个不同表情和姿势的卡通角色，每个贴纸都有白色边框，色彩鲜艳，风格统一。`,
      tags: ["动漫", "AI生成"],
      source: "@richardchang",
      previewImage: "https://camo.githubusercontent.com/bbd003c3b5e1edffb792e0d7a8260362459d71788fc94beff3f84546ebb23f77/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f6a616d657a2d626f6e646f732f617765736f6d652d677074346f2d696d616765732f63617365732f33312f6578616d706c655f6e617275746f5f737469636b6572732e706e67",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-6540b5",
      title: "名画人物麦片广告",
      titleEn: "名画人物麦片广告",
      description: "名画人物麦片广告",
      prompt: `《大师麦片》：根据我上传的照片的人物特征判断，为他生成一个符合他特质的燕麦片搭配（比如蔬菜、水果、酸奶、粗粮等等）和包装设计，然后生成他作为麦片包装盒封面人物 加 相应麦片搭配的广告封面，人物要保持特征、可爱Q版3d、c4d渲染风格，麦片所放置的地方的风格也要符合设定，比如放在厨房、超市 极简主义的设计台上等等，先做好设定，再生成图像。`,
      tags: ["AI生成"],
      source: "@ZHO_ZHO_ZHO",
      previewImage: "https://camo.githubusercontent.com/59fa9dc7aacd8eae0a665dd4788cab4e67fcded679534808e64b4316d073da12/68747470733a2f2f626962696770742d617070732e636861747669642e61692f63686174696d672f67656d696e692d417775655a65342d4b35546d7346546467574549562e706e673f763d31",
      nodeTemplate: { requiresImageInput: true, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-0387a0",
      title: "手办真人同框合影",
      titleEn: "手办真人同框合影",
      description: "手办真人同框合影",
      prompt: `以手机随手拍摄的日常风格，桌面上摆放着一款 【成龙】动漫手办，动作夸张帅气，装备齐全。同时，真实世界的对应人物也出现在镜头中，与手办摆出相似的姿势，形成手办与真实人物同框的有趣对比效果。整体构图和谐自然，传递温暖且富有生活气息的视觉体验。`,
      tags: ["AI生成"],
      source: "@dotey",
      previewImage: "https://camo.githubusercontent.com/02ca170c19bd1e53e2042d9f64da3e8f0d60892087d0627aa411a6a19b57165d/68747470733a2f2f626962696770742d617070732e636861747669642e61692f63686174696d672f67656d696e692d72657472792d6254544e6171486d487a4d4d70773849594d4d34512e706e673f763d31",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-7e913a",
      title: "讽刺海报生成",
      titleEn: "讽刺海报生成",
      description: "讽刺海报生成",
      prompt: `为我生成讽刺海报：GPT 4o 狂卷，都别干图像AI了 还是送外卖吧`,
      tags: ["海报", "AI生成"],
      source: "@ZHO_ZHO_ZHO",
      previewImage: "https://camo.githubusercontent.com/8196596a8cd42fb558ff6d837c11acc9b045ed52950018f48aecd6f9baea1660/68747470733a2f2f626962696770742d617070732e636861747669642e61692f63686174696d672f67656d696e692d72657472792d78476d4e673168674a59307579467433727a32634b2e706e673f763d31",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
    {
      id: "p-e0e143",
      title: "奇幻水下场景冰棒",
      titleEn: "奇幻水下场景冰棒",
      description: "奇幻水下场景冰棒",
      prompt: `倾斜的第一人称视角拍摄，一只手握着一支超现实的冰棒。冰棒有着透明的蓝色外壳，里面展现了一个水下场景：一个小潜水员、几条小鱼和漂浮的气泡，还有翻滚的海浪，一根绿色的冰棒棍贯穿中心。冰棒略微融化，底部是一根木棍，手正握着这根木棍。背景是柔焦的纽约街景，采用高端产品摄影风格。`,
      tags: ["场景", "AI生成"],
      source: "@madpencil_",
      previewImage: "https://camo.githubusercontent.com/1aa5213feeea6cc3523485a64ad969460b11922621efc8983854ef0f3f19489a/68747470733a2f2f626962696770742d617070732e636861747669642e61692f63686174696d672f67656d696e692d736c654d554a47305f736d665968554a3078397a6b2e706e673f763d31",
      nodeTemplate: { requiresImageInput: false, generatorType: "pro", aspectRatio: "1:1" },
    },
  ],
};
